---
name: Deploy

on:
  workflow_run:
    branches: [master]
    types: [completed]
    workflows: [Nix Flake Check]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true

          files: |
            LICENSE
            result/**

          tag_name: 'latest'
          token: "${{ secrets.GITHUB_TOKEN }}"
